---
- name: Install Nginx
  hosts: localhost
  become: yes

  tasks:
    - name: Install Nginx
      apt:
        name: nginx
        state: present


    - name: running nginx
      service:
        name: nginx
        state: started
        enabled: true

    - name: Create index.html
      copy:
        content: "Hello Ansible"
        dest: /var/www/html/index.html
        mode: "0644"

